version: '3.1'

services:

  hubot:
    container_name: hubot
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - http_proxy
        - https_proxy
        - no_proxy
    env_file:
      - hubot.env
    restart: always
